name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python -m pip install -r requirements.txt

      - name: Byte-compile sources
        run: |
          python - <<'PY'
          import compileall, sys
          ok = compileall.compile_dir('src', force=True, quiet=0)
          sys.exit(0 if ok else 1)
          PY

      - run: python -m pip install pytest
      - run: pytest -q
